version: "3.8"

services:
  db:
    image: "postgres"
    container_name: "greenlight-database"
    ports:
      - "5432:5432"
    expose:
      - 5432
    environment:
      - POSTGRES_DB=greenlight
      - POSTGRES_USER=greenlight
      - POSTGRES_PASSWORD=postgres
    volumes:
      - database_postgres:/var/lib/postgresql/data
volumes:
  database_postgres:
